export const GET_USER_INFO = 'GET_USER_INFO'
export const GET_POST_LIST = 'GET_POST_LIST'
export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const REFRESH_LOADING = 'REFRESH_LOADING'